
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Windows -  - arm64
      The host system is: Darwin - 23.6.0 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/clang 
      Build flags: -march=armv8.7-a;-fvectorize;-ffp-model=fast;-fno-finite-math-only;-Wno-format;-Wno-unused-variable;-Wno-unused-function;-Wno-gnu-zero-variadic-macro-arguments
      Id flags: -c;--target=arm64-pc-windows-msvc 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /Users/omarmena/Research/testing/llama.cpp/build-arm64-windows-llvm-debug/CMakeFiles/3.29.5/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/clang++ 
      Build flags: -march=armv8.7-a;-fvectorize;-ffp-model=fast;-fno-finite-math-only;-Wno-format;-Wno-unused-variable;-Wno-unused-function;-Wno-gnu-zero-variadic-macro-arguments
      Id flags: -c;--target=arm64-pc-windows-msvc 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /Users/omarmena/Research/testing/llama.cpp/build-arm64-windows-llvm-debug/CMakeFiles/3.29.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/clang 
      Build flags: -march=armv8.7-a;-fvectorize;-ffp-model=fast;-fno-finite-math-only;-Wno-format;-Wno-unused-variable;-Wno-unused-function;-Wno-gnu-zero-variadic-macro-arguments
      Id flags: -c;--target=arm64-pc-windows-msvc 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /Users/omarmena/Research/testing/llama.cpp/build-arm64-windows-llvm-debug/CMakeFiles/3.29.5/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/clang++ 
      Build flags: -march=armv8.7-a;-fvectorize;-ffp-model=fast;-fno-finite-math-only;-Wno-format;-Wno-unused-variable;-Wno-unused-function;-Wno-gnu-zero-variadic-macro-arguments
      Id flags: -c;--target=arm64-pc-windows-msvc 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /Users/omarmena/Research/testing/llama.cpp/build-arm64-windows-llvm-debug/CMakeFiles/3.29.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/local/Cellar/cmake/3.29.5/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
...
